# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user/v1/user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user/v1/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user/v1/user.proto\x12\x07user.v1\"0\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"V\n\x12\x43reateUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\t\"!\n\x0eGetUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"g\n\x0fGetUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\t\x12\x12\n\nupdated_at\x18\x05 \x01(\t\"\x12\n\x10ListUsersRequest\"<\n\x11ListUsersResponse\x12\'\n\x05users\x18\x01 \x03(\x0b\x32\x18.user.v1.GetUserResponse\"A\n\x11UpdateUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"V\n\x12UpdateUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x12\n\nupdated_at\x18\x04 \x01(\t\"$\n\x11\x44\x65leteUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"9\n\x12\x44\x65leteUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\ndeleted_at\x18\x02 \x01(\t2\xe4\x02\n\x0bUserService\x12\x45\n\nCreateUser\x12\x1a.user.v1.CreateUserRequest\x1a\x1b.user.v1.CreateUserResponse\x12<\n\x07GetUser\x12\x17.user.v1.GetUserRequest\x1a\x18.user.v1.GetUserResponse\x12\x42\n\tListUsers\x12\x19.user.v1.ListUsersRequest\x1a\x1a.user.v1.ListUsersResponse\x12\x45\n\nUpdateUser\x12\x1a.user.v1.UpdateUserRequest\x1a\x1b.user.v1.UpdateUserResponse\x12\x45\n\nDeleteUser\x12\x1a.user.v1.DeleteUserRequest\x1a\x1b.user.v1.DeleteUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user.v1.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEUSERREQUEST']._serialized_start=31
  _globals['_CREATEUSERREQUEST']._serialized_end=79
  _globals['_CREATEUSERRESPONSE']._serialized_start=81
  _globals['_CREATEUSERRESPONSE']._serialized_end=167
  _globals['_GETUSERREQUEST']._serialized_start=169
  _globals['_GETUSERREQUEST']._serialized_end=202
  _globals['_GETUSERRESPONSE']._serialized_start=204
  _globals['_GETUSERRESPONSE']._serialized_end=307
  _globals['_LISTUSERSREQUEST']._serialized_start=309
  _globals['_LISTUSERSREQUEST']._serialized_end=327
  _globals['_LISTUSERSRESPONSE']._serialized_start=329
  _globals['_LISTUSERSRESPONSE']._serialized_end=389
  _globals['_UPDATEUSERREQUEST']._serialized_start=391
  _globals['_UPDATEUSERREQUEST']._serialized_end=456
  _globals['_UPDATEUSERRESPONSE']._serialized_start=458
  _globals['_UPDATEUSERRESPONSE']._serialized_end=544
  _globals['_DELETEUSERREQUEST']._serialized_start=546
  _globals['_DELETEUSERREQUEST']._serialized_end=582
  _globals['_DELETEUSERRESPONSE']._serialized_start=584
  _globals['_DELETEUSERRESPONSE']._serialized_end=641
  _globals['_USERSERVICE']._serialized_start=644
  _globals['_USERSERVICE']._serialized_end=1000
# @@protoc_insertion_point(module_scope)
