# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment/v1/payment.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'payment/v1/payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18payment/v1/payment.proto\x12\npayment.v1\"\xd8\x01\n\x14\x43reatePaymentRequest\x12\x0e\n\x06\x61mount\x18\x01 \x01(\t\x12\x10\n\x08\x63urrency\x18\x02 \x01(\t\x12\x13\n\x0b\x63ustomer_id\x18\x03 \x01(\t\x12\x16\n\x0epayment_method\x18\x04 \x01(\t\x12@\n\x08metadata\x18\x05 \x03(\x0b\x32..payment.v1.CreatePaymentRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"O\n\x15\x43reatePaymentResponse\x12\x12\n\npayment_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x12\n\ncreated_at\x18\x03 \x01(\t\"\'\n\x11GetPaymentRequest\x12\x12\n\npayment_id\x18\x01 \x01(\t\"n\n\x12GetPaymentResponse\x12\x12\n\npayment_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\t\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\t\";\n\x15ProcessPaymentRequest\x12\x12\n\npayment_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\"R\n\x16ProcessPaymentResponse\x12\x12\n\npayment_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x14\n\x0cprocessed_at\x18\x03 \x01(\t\"\x14\n\x12HealthCheckRequest\"8\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t2\xdc\x02\n\x0ePaymentService\x12T\n\rCreatePayment\x12 .payment.v1.CreatePaymentRequest\x1a!.payment.v1.CreatePaymentResponse\x12K\n\nGetPayment\x12\x1d.payment.v1.GetPaymentRequest\x1a\x1e.payment.v1.GetPaymentResponse\x12W\n\x0eProcessPayment\x12!.payment.v1.ProcessPaymentRequest\x1a\".payment.v1.ProcessPaymentResponse\x12N\n\x0bHealthCheck\x12\x1e.payment.v1.HealthCheckRequest\x1a\x1f.payment.v1.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment.v1.payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEPAYMENTREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_CREATEPAYMENTREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_CREATEPAYMENTREQUEST']._serialized_start=41
  _globals['_CREATEPAYMENTREQUEST']._serialized_end=257
  _globals['_CREATEPAYMENTREQUEST_METADATAENTRY']._serialized_start=210
  _globals['_CREATEPAYMENTREQUEST_METADATAENTRY']._serialized_end=257
  _globals['_CREATEPAYMENTRESPONSE']._serialized_start=259
  _globals['_CREATEPAYMENTRESPONSE']._serialized_end=338
  _globals['_GETPAYMENTREQUEST']._serialized_start=340
  _globals['_GETPAYMENTREQUEST']._serialized_end=379
  _globals['_GETPAYMENTRESPONSE']._serialized_start=381
  _globals['_GETPAYMENTRESPONSE']._serialized_end=491
  _globals['_PROCESSPAYMENTREQUEST']._serialized_start=493
  _globals['_PROCESSPAYMENTREQUEST']._serialized_end=552
  _globals['_PROCESSPAYMENTRESPONSE']._serialized_start=554
  _globals['_PROCESSPAYMENTRESPONSE']._serialized_end=636
  _globals['_HEALTHCHECKREQUEST']._serialized_start=638
  _globals['_HEALTHCHECKREQUEST']._serialized_end=658
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=660
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=716
  _globals['_PAYMENTSERVICE']._serialized_start=719
  _globals['_PAYMENTSERVICE']._serialized_end=1067
# @@protoc_insertion_point(module_scope)
