# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from payment.v1 import payment_pb2 as payment_dot_v1_dot_payment__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in payment/v1/payment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PaymentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePayment = channel.unary_unary(
                '/payment.v1.PaymentService/CreatePayment',
                request_serializer=payment_dot_v1_dot_payment__pb2.CreatePaymentRequest.SerializeToString,
                response_deserializer=payment_dot_v1_dot_payment__pb2.CreatePaymentResponse.FromString,
                _registered_method=True)
        self.GetPayment = channel.unary_unary(
                '/payment.v1.PaymentService/GetPayment',
                request_serializer=payment_dot_v1_dot_payment__pb2.GetPaymentRequest.SerializeToString,
                response_deserializer=payment_dot_v1_dot_payment__pb2.GetPaymentResponse.FromString,
                _registered_method=True)
        self.ListPayments = channel.unary_unary(
                '/payment.v1.PaymentService/ListPayments',
                request_serializer=payment_dot_v1_dot_payment__pb2.ListPaymentsRequest.SerializeToString,
                response_deserializer=payment_dot_v1_dot_payment__pb2.ListPaymentsResponse.FromString,
                _registered_method=True)
        self.ProcessPayment = channel.unary_unary(
                '/payment.v1.PaymentService/ProcessPayment',
                request_serializer=payment_dot_v1_dot_payment__pb2.ProcessPaymentRequest.SerializeToString,
                response_deserializer=payment_dot_v1_dot_payment__pb2.ProcessPaymentResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/payment.v1.PaymentService/HealthCheck',
                request_serializer=payment_dot_v1_dot_payment__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=payment_dot_v1_dot_payment__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class PaymentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreatePayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPayments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessPayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePayment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePayment,
                    request_deserializer=payment_dot_v1_dot_payment__pb2.CreatePaymentRequest.FromString,
                    response_serializer=payment_dot_v1_dot_payment__pb2.CreatePaymentResponse.SerializeToString,
            ),
            'GetPayment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPayment,
                    request_deserializer=payment_dot_v1_dot_payment__pb2.GetPaymentRequest.FromString,
                    response_serializer=payment_dot_v1_dot_payment__pb2.GetPaymentResponse.SerializeToString,
            ),
            'ListPayments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPayments,
                    request_deserializer=payment_dot_v1_dot_payment__pb2.ListPaymentsRequest.FromString,
                    response_serializer=payment_dot_v1_dot_payment__pb2.ListPaymentsResponse.SerializeToString,
            ),
            'ProcessPayment': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessPayment,
                    request_deserializer=payment_dot_v1_dot_payment__pb2.ProcessPaymentRequest.FromString,
                    response_serializer=payment_dot_v1_dot_payment__pb2.ProcessPaymentResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=payment_dot_v1_dot_payment__pb2.HealthCheckRequest.FromString,
                    response_serializer=payment_dot_v1_dot_payment__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'payment.v1.PaymentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('payment.v1.PaymentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PaymentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.v1.PaymentService/CreatePayment',
            payment_dot_v1_dot_payment__pb2.CreatePaymentRequest.SerializeToString,
            payment_dot_v1_dot_payment__pb2.CreatePaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.v1.PaymentService/GetPayment',
            payment_dot_v1_dot_payment__pb2.GetPaymentRequest.SerializeToString,
            payment_dot_v1_dot_payment__pb2.GetPaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPayments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.v1.PaymentService/ListPayments',
            payment_dot_v1_dot_payment__pb2.ListPaymentsRequest.SerializeToString,
            payment_dot_v1_dot_payment__pb2.ListPaymentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessPayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.v1.PaymentService/ProcessPayment',
            payment_dot_v1_dot_payment__pb2.ProcessPaymentRequest.SerializeToString,
            payment_dot_v1_dot_payment__pb2.ProcessPaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.v1.PaymentService/HealthCheck',
            payment_dot_v1_dot_payment__pb2.HealthCheckRequest.SerializeToString,
            payment_dot_v1_dot_payment__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
